### ISSUE TITLE
cy freezes after adding "(cy/set :animate true)" to config

### ISSUE THREAD

**Issue by olivewong** [cfoust/cy#5]
copied from the example https://cfoust.github.io/cy/parameters.html:
```
$ cat $HOME/cy/cyrc.janet
(cy/set :animate true)
```
with animate (since it was disabled on ssh). After adding this and running `cy`, it goes to a blank screen where nothing is registered (sorry, not sure where cy logs are stored or I'd try to find those for you - I remember seeing there was a diagnostics pane but am not able to open since cy is frozen). I've tried re-running cy. most of the rest of the quickstart was running before adding this!
I'm using bash on Ubuntu 20.04.5 LTS, cy installed from latest source

**Comment by cfoust** [comment]
Found a fix for this! Should be out in the next release. Thank you for reporting!
